# Generated by Django 5.0.6 on 2024-06-25 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(default=datetime.date.today)),
                ("title", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="videos"),
                ),
                (
                    "thumbnail",
                    models.FileField(blank=True, null=True, upload_to="thumbnails"),
                ),
                ("video_480p", models.CharField(blank=True, max_length=255, null=True)),
                ("video_720p", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
