# Generated by Django 5.0.6 on 2024-06-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="movie",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=(
                    "C:\\Users\\cwestrich\\Downloads\\coding\\developeracademy\\Backend\\Videoflix-Backend\\media",
                    "thumbnails",
                ),
            ),
        ),
    ]
