# Generated by Django 5.0.6 on 2024-06-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_remove_movie_picture_movie_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="movie",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/",
                verbose_name="Category picture",
            ),
        ),
    ]
