# Generated by Django 5.0.6 on 2024-06-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_remove_movie_thumbnail_movie_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="picture",
        ),
        migrations.AddField(
            model_name="movie",
            name="thumbnail",
            field=models.FileField(blank=True, null=True, upload_to="thumbnails"),
        ),
    ]
